spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username:root
    password:Krishna@9097
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server.port: 9097
